#!/bin/bash


/Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviews -d file://docs0.zip -f sample -g %courseId%
/Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviews -d file://docs1.zip -f sample -g %courseId%
/Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviews -d file://docs2.zip -f sample -g %courseId%
/Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviews -d file://docs3.zip -f sample -g %courseId%
/Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviews -d file://docs4.zip -f sample -g %courseId%
/Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviews -d file://docs5.zip -f sample -g %courseId%
/Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviews -d file://docs6.zip -f sample -g %courseId%
/Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviews -d file://docs7.zip -f sample -g %courseId%
/Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviews -d file://docs8.zip -f sample -g %courseId%
/Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviews -d file://docs9.zip -f sample -g %courseId%

/Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviewers -d file://reviewerdocs0.zip -f sample -g %reviewerId%
/Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviewers -d file://reviewerdocs1.zip -f sample -g %reviewerId%
/Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviewers -d file://reviewerdocs2.zip -f sample -g %reviewerId%
/Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviewers -d file://reviewerdocs3.zip -f sample -g %reviewerId%
/Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviewers -d file://reviewerdocs4.zip -f sample -g %reviewerId%
/Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviewers -d file://reviewerdocs5.zip -f sample -g %reviewerId%
/Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviewers -d file://reviewerdocs6.zip -f sample -g %reviewerId%
/Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviewers -d file://reviewerdocs7.zip -f sample -g %reviewerId%
/Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviewers -d file://reviewerdocs8.zip -f sample -g %reviewerId%
/Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviewers -d file://reviewerdocs9.zip -f sample -g %reviewerId%