#!/bin/bash


/Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-courses -d file://courses1.json -f list -g %courseId%
# /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-courses -d file://courseDocs1.zip -f sample -g %courseId%
# /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-courses -d file://courseDocs2.zip -f sample -g %courseId%
# /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-courses -d file://courseDocs3.zip -f sample -g %courseId%
# /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-courses -d file://courseDocs4.zip -f sample -g %courseId%
# /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-courses -d file://courseDocs5.zip -f sample -g %courseId%
# /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-courses -d file://courseDocs6.zip -f sample -g %courseId%
# /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-courses -d file://courseDocs7.zip -f sample -g %courseId%
# /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-courses -d file://courseDocs8.zip -f sample -g %courseId%
# /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-courses -d file://courseDocs9.zip -f sample -g %courseId%

/Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviews -d file://reviews1.json -f list -g %reviewId%
# /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviews -d file://reviewDocs1.zip -f sample -g %reviewId%
# /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviews -d file://reviewDocs2.zip -f sample -g %reviewId%
# /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviews -d file://reviewDocs3.zip -f sample -g %reviewId%
# /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviews -d file://reviewDocs4.zip -f sample -g %reviewId%
# /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviews -d file://reviewDocs5.zip -f sample -g %reviewId%
# /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviews -d file://reviewDocs6.zip -f sample -g %reviewId%
# /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviews -d file://reviewDocs7.zip -f sample -g %reviewId%
# /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviews -d file://reviewDocs8.zip -f sample -g %reviewId%
# /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviews -d file://reviewDocs9.zip -f sample -g %reviewId%

/Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviewers -d file://reviewers1.json -f list -g %reviewerId%
# /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviewers -d file://reviewerdocs1.zip -f sample -g %reviewerId%
# /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviewers -d file://reviewerdocs2.zip -f sample -g %reviewerId%
# /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviewers -d file://reviewerdocs3.zip -f sample -g %reviewerId%
# /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviewers -d file://reviewerdocs4.zip -f sample -g %reviewerId%
# /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviewers -d file://reviewerdocs5.zip -f sample -g %reviewerId%
# /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviewers -d file://reviewerdocs6.zip -f sample -g %reviewerId%
# /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviewers -d file://reviewerdocs7.zip -f sample -g %reviewerId%
# /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviewers -d file://reviewerdocs8.zip -f sample -g %reviewerId%
# /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/cbimport json -c couchbase://127.0.0.1 -u $CB_REST_USERNAME -p $CB_REST_PASSWORD -b rpt27-sdc-websockets-reviewers -d file://reviewerdocs9.zip -f sample -g %reviewerId%